<?php

function data_importer_menu() {
  $items = array();
  $items['staff/import-data'] = array(
    'title' => 'Import Data',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('data_importer_import_form'),
    'access arguments' => array('access people listing'),
    'weight' => 3,
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

function data_importer_import_form($form,&$form_state) {
  $form['markup'] = array(
    '#type' => 'markup',
    '#markup' => 'Include a header with title, type, and field names.',
    '#prefix' => '<p><strong>',
    '#suffix' => '</strong></p>',
  );
  $form['csv'] = array(
    '#type' => 'file',
    '#title' => "Upload a CSV",
    '#tree' => TRUE,
  );
  $last = variable_get("data_importer_last",false);
  if ($last) {
    $form['last'] = array(
      '#type' => 'item',
      '#markup' => 'Last file uploaded: '.$last,
    );
  }
  $form['process'] = array(
    '#type' => 'radios',
    '#title' => 'How to Process this CSV',
    '#options' => array(
      'dry' => 'Dry run only',
      'update'=>'Update existing Drupal nodes only, overwriting with data from this CSV.',
      'make'=>'Create nodes using CSV data, but do not update existing Drupal nodes.',
      'accessid' => 'Assign Access ID only',
    ),
    '#default_value' => 'dry',
  );
  $form['source'] = array(
    '#type' => 'radios',
    '#title' => 'Source of this CSV',
    '#options' => array(
      'excel' => 'Custom spreadsheet',
      'access' => 'Access database with PersonID column',
    ),
    '#default_value' => 'excel',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Process CSV',
    '#submit' =>  array('data_importer_import_form_submit')
  );
  $form['expunge'] = array(
    '#type' => 'submit',
    '#prefix' => '&nbsp;&nbsp;',
    '#value' => 'Expunge previously uploaded files',
    '#submit' =>  array('data_importer_expunge')
  );
  return $form;
}

function data_importer_expunge() {
  if (file_exists(drupal_realpath("public://data_importer"))) {
    file_unmanaged_delete_recursive("public://data_importer");
    drupal_mkdir("public://data_importer");
  }
  variable_del("data_importer_last");
  drupal_set_message("Previous uploads expunged.");
}

function data_importer_import_form_submit($form, &$form_state) {
  if (module_exists("rules")) {
    module_disable(array("rules","rules_admin"));
    drupal_set_message("Suspending the rules.");
  }
  $process = $form_state['input']['process'];
  $source =  $form_state['input']['source'];
  if (!file_exists(drupal_realpath("public://data_importer"))) {
    drupal_mkdir("public://data_importer");
  }
  $file = file_save_upload(
    'csv',
    array(
      'file_validate_extensions' => array('csv'),
    ),
    'public://data_importer',
    FILE_EXISTS_REPLACE
  );
  if (!$file) {
    $last = variable_get("data_importer_last",false);
    if ($last) {
      if (file_exists($last)) {
        $path = $last;
        drupal_set_message("Using last file uploaded.");
      }
      else {
        variable_del("data_importer_last");
        drupal_set_message("Couldn't access last file uploaded and no file present in this attempt.","error");
        return;
      }
    }
    else {
      drupal_set_message("File could not be parsed.","error");
      return;
    }
  }
  else {
    $path = drupal_realpath($file->destination);
  }
  variable_set("data_importer_last",$path);
  $csv = explode("\n",str_replace("\r","\n",file_get_contents($path))); 
  $header = str_getcsv($csv[0]);
  if (!in_array("type",$header)) {
    drupal_set_message("No type column exists and cannot determine from file.",'error');
    return;
  }
  unset($csv[0]);
  $array = array();
  foreach ($csv as $row) {
    $sub = array();
    $data = str_getcsv($row);
    foreach ($data as $key => $value) {
      $sub[$header[$key]] = $value;
    }
    $array[] = $sub;
  }
  foreach ($array as $item) {
    $node = false;
    // Try to find an existing nid via access_ids table
    if ($source == "access") {
      if ($item['type'] == "person") {
        $access_id = data_importer_fetch_asc($item['PersonID']);
      }
      $node = ($access_id ? node_load($access_id->nid) : false);
    }
    // If no node is found via imported data, try to find one with matching data
    if (!$node) {
      if ($item['type'] == "person") {
        $node = person_find_person(
          $item['field_person_first_name']." ".
          $item['field_person_middle_name']." ".
          $item['field_person_last_name'],
          $item['field_person_email_pref']);
      }
      else {
        $query = db_select('node','n')
          ->fields('n',array('nid'));
        if ($item['type'] == "parish") {
          $query->condition('n.title',$item['field_parish_home_city'].', '.$item['title']);
        }
        $result = $query->execute();
        while ($record = $result->fetchAssoc()) {
          $node = node_load($record['nid']);
        }
      }
    }
    if ($node) {
      foreach ($item as $key => $cell) {
        $key = strtolower(preg_replace("/[^A-Za-z0-9_]/", '', $key));
        if ($key <> "title" && $key <> "type" && $key <> "status") {
          eval("\$key_exists = isset(\$node->".$key.");");
          if ($key_exists) {
            if ($cell == "FALSE") {
              $cell = 0;
            }
            elseif ($cell == "TRUE") {
              $cell = 1;
            }
            if ($cell === 0) {
              eval("\$node->".$key." = 'und';");
            }
            else {
              eval("\$node->".$key." = array('und'=>array(0=>array('value'=>\"".$cell."\")));");
            }
          }
        }
      }
      if (!isset($node->title)) {
        $node->title = $item['field_person_first_name']." ".
          $item['field_person_middle_name']." ".
          $item['field_person_last_name'];
      }
      if ($process == "dry") {
        if (isset($node->nid)) {
          drupal_set_message("DRY RUN - Updated node ".$node->title." (".$node->nid.").");
        }
        else {
          drupal_set_message("DRY RUN - Created ".$node->title);
        }
      }
      elseif ($process == "update") {
        $node->title = person_get_full_name($node);
        node_save($node);
        drupal_set_message("Updated node ".$node->title." (".$node->nid.").");
      }
    }
    // No node found
    else {
      if ($process == "dry" || $process == "update") {
        drupal_set_message("No node found for ".
          $item['field_person_first_name']." ".
          $item['field_person_middle_name']." ".
          $item['field_person_last_name'],
          "error"
        );
      }
      elseif ($process == "make") {
        $node = new StdClass();
        $node->bundle = $item['type'];
        $node->type = $item['type'];
        $node->language = 'und';
        node_object_prepare($node);
        foreach ($item as $key => $cell) {
          $key = strtolower(preg_replace("/[^A-Za-z0-9_]/", '', $key));
          if (field_info_instance("node",$key,$item['type'])) {
            eval("\$node->".$key."['und'][0]['value'] = \"".$cell."\";");
          }
        }
        $node->title = person_get_full_name($node);
        node_save($node);
        drupal_set_message("Created node ".$node->title." (".$node->nid.").");
      }
    }
    // Associate with an Access ID, if a node exists
    if (isset($node->nid) && ($process == "accessid" || $process == "make")) {
      data_importer_write_asc($item['PersonID'],$node->nid);
    }
  }
  $form_state['rebuild'] = TRUE;  
  if (!module_exists("rules")) {
    module_enable(array("rules","rules_admin"));
    drupal_set_message("Engaging the rules.");
  }
  cache_clear_all();
}

function data_importer_write_asc($id,$nid) {
  $data = array(
    'access_id' => $id,
    'nid' => $nid,
  );
  $existing = data_importer_fetch_asc(FALSE,$nid);
  if ($existing) {
    $data['asc_id'] = $existing->asc_id;
    drupal_write_record("access_ids",$data,array('asc_id'));
  }
  else {
    drupal_write_record("access_ids",$data);
  }
  drupal_set_message("Connecting node ".$nid." to ID ".$id);
}

function data_importer_fetch_asc($id=FALSE,$nid=FALSE) {
  $query = db_select('access_ids','a')
    ->fields('a',array('asc_id','nid','access_id'));
  $or = db_or()
    ->condition('a.access_id',$id)
    ->condition('a.nid',$nid);
  $query->condition($or);
  $result = $query->execute();
  while ($record = $result->fetchObject()) {
    return $record;
  }
  return false;
}

function data_importer_node_load($nodes, $types) {
  foreach ($nodes as $node) {
    $asc = data_importer_fetch_asc(FALSE,$node->nid);
    if (isset($asc->access_id)) {
      $node->access_id = $asc->access_id;
    }
  }
}
