<?php
/**
 * @file
 * Code for the Prayer Requests feature.
 */

include_once 'prayer_requests.features.inc';


function prayer_requests_menu() {
  $items = array();
  $items['prayers'] = array(
    'title' => 'EDOR Prayer Requests',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('prayer_requests_view_form',"all"),
    'access arguments' => array('access clergy directory'),
  );
  $items['prayers/directory'] = array(
    'title' => 'Directory Site Prayers',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('prayer_requests_view_form','directory'),
    'access arguments' => array('access clergy directory'),
    'weight' => 0,
    'type' => MENU_LOCAL_TASK,
  );
  $items['prayers/needs'] = array(
    'title' => 'Prayer Needs Blast',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('prayer_requests_view_form','prayerneeds'),
    'access arguments' => array('access clergy directory'),
    'weight' => 1,
    'type' => MENU_LOCAL_TASK,
  );
  $items['prayers/newsletter'] = array(
    'title' => 'Newsletter',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('prayer_requests_view_form','newsletter'),
    'access arguments' => array('access clergy directory'),
    'weight' => 2,
    'type' => MENU_LOCAL_TASK,
  );
  $items['prayers/web'] = array(
    'title' => 'Web',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('prayer_requests_view_form','web'),
    'access arguments' => array('access clergy directory'),
    'weight' => 3,
    'type' => MENU_LOCAL_TASK,
  );
  $items['web-prayers'] = array(
    'title' => 'Public Prayer List',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('prayer_requests_view_form','web'),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['prayers/all'] = array(
    'title' => 'All Active Prayers',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('prayer_requests_view_form','all'),
    'access arguments' => array('access clergy directory'),
    'weight' => -1,
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['prayers/add'] = array(
    'title' => 'New Prayer Request',
    'page callback' => 'drupal_goto',
    'page arguments' => array('node/add/prayer'),
    'access arguments' => array('access clergy directory'),
    'weight' => 10,
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/structure/prayers'] = array(
    'title' => 'Prayer Request settings',
    'description' => 'Manage boilerplate text for prayers and other settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('prayer_requests_admin_form'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

function prayer_requests_admin_form($form,&$form_state) {
  $types = prayer_requests_types();
  foreach ($types as $key => $value) {
    $form[$key] = array(
      '#type' => 'fieldset',
      '#title' => $value,
    );
    $form[$key][$key."_prefix"] = array(
      '#type' => 'textarea',
      '#title' => 'Text before prayers',
      '#default_value' => variable_get($key."_prefix",""),
    );
    $form[$key][$key."_suffix"] = array(
      '#type' => 'textarea',
      '#title' => 'Text after prayers',
      '#default_value' => variable_get($key."_suffix",""),
    );
  }
  return system_settings_form($form);
}

function prayer_requests_view_form($form,&$form_state,$location = "all") {
  $prayers = prayer_requests_fetch($location);
  if (!$prayers) {
    $form['markup'] = array(
      '#type' => 'item',
      '#markup' => 'No prayers at present.',
    );
  }
  else {
    $types = prayer_requests_types();
    foreach ($prayers as $prayer) {
      $type = $prayer->field_prayer_type['und'][0]['value'];
      if (!isset($form[$type])) {
        $prefix = variable_get($type."_prefix","");
        $suffix = variable_get($type."_suffix","");
        $form[$type] = array(
          '#type' => 'container',
          '#prefix' => '<br /><h2>'.$types[$type].'</h2>'.$prefix.'<ul>',
          '#suffix' => '</ul>'.$suffix,
        );
      }
      $body = $prayer->body['und'][0]['value'];
      if (node_access("update",$prayer) && $location == "all") {
        $body .= " ".l("edit","node/".$prayer->nid."/edit");
      }
      if (node_access("delete",$prayer) && $location == "all") {
        $body .= " ".l("delete","node/".$prayer->nid."/delete");
      }
      $form[$type][] = array(
        '#type' => 'item',
        '#markup' => $body,
        '#prefix' => '<li>',
        '#suffix' => '</li>',
      );
    }
  }
  return $form;
}

function prayer_requests_form_prayer_node_form_alter(&$form,&$form_state,$form_id) {
  $form['field_prayer_type']['und']['#options'] = array_filter(prayer_requests_types());
  if (isset($form['field_prayer_type']['und']['#entity']->field_prayer_type['und'][0]['value'])) {
    $form['field_prayer_type']['und']['#default_value'] = $form['field_prayer_type']['und']['#entity']->field_prayer_type['und'][0]['value'];
  }

}

function prayer_requests_types() {
  return array(
    'general'=>'Prayers and Petitions',
    'thanksgiving'=>'Thanksgivings',
    'peace'=>'Prayers for peace in the world',
    'parish'=>'Parishes in transition',
    'died' => 'For those who have died',
  );
}

function prayer_requests_fetch($location = "all") {
  $now = date("Y-m-d")."T00:00:00";
  $query = db_select("node","n");
  $query->leftJoin("field_data_field_prayer_type","t","t.entity_id = n.nid");
  $query->leftJoin("field_data_field_prayer_start","s","s.entity_id = n.nid");
  $query->leftJoin("field_data_field_prayer_end","e","e.entity_id = n.nid");
  $query->leftJoin("field_data_body","b","b.entity_id = n.nid");
  $query->fields('n',array('nid'))
    ->condition('n.type','prayer')
    ->condition('status',1);
  if ($location <> "all") {
    $query->leftJoin("field_data_field_prayer_location","l","l.entity_id = n.nid");
    $query->condition('l.field_prayer_location_value',$location);
  }
  $start = db_or()
    ->condition('s.field_prayer_start_value',$now,'<=')
    ->isNull('s.field_prayer_start_value');
  $query->condition($start);

  $end = db_or()
    ->condition('e.field_prayer_end_value',$now,'>=')
    ->isNull('e.field_prayer_end_value');
  $query->condition($end);
  $query->orderBy("t.field_prayer_type_value","ASC")
    ->orderBy("b.body_value","ASC");
  $result = $query->execute();
  if (!$result) {
    return false;
  }
  else {
    $prayers = array();
    while ($record = $result->fetchAssoc()) {
      $prayers[] = node_load($record['nid']);
    }
    return $prayers;
  }
}
