<?php
/**
 * Implementation of hook_menu
 */

function mydata_menu() {
  $menu['my-data'] = array(
    'title' => "My Data",
    'description' => "Page showing user's data",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mydata_page_form'),
    'access arguments' => array ('access content'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $menu;
}

function mydata_init() {
  variable_set("site_frontpage","my-data");
}

function mydata_page_form($form,&$form_state) {
  global $user;
  $query = db_select('node','n')
    ->fields('n',array('nid','type','title','changed'))
    ->condition('status','1')
    ->orderBy('type','ASC')
    ->orderBy('changed','ASC');
  if ($user->uid <> 1 && !in_array('database editor', $user->roles) && !in_array('administrator', $user->roles)){
    $query->condition('uid',$user->uid);
  }
  $result = $query->execute();
  $tables = array();
  $variables = array(
    'header' => array('Record','Last Edited','edit'),
    'rows' => array(),
    'attributes' => array(),
    'caption' => '',
    'colgroups' => array(),
    'sticky' => FALSE,
    'empty' => '',
  );
  while ($record = $result->fetchAssoc()) {
    if (!isset($tables[$record['type']])) {
      $type = $record['type'];
      $tables[$type] = $variables;
      $tables[$type]['caption'] = ucwords(str_replace("_"," ",$type))." Records";
    }
    $row = array(
      'data' => array(
        l($record['title'],"node/".$record['nid']),
        date('r',$record['changed']),
        l("edit","node/".$record['nid']."/edit"),
        ),
      );
    $tables[$type]['rows'][] = $row;
  }
  $count = 1;
  foreach ($tables as $table) {
    $form['table'.$count] = array(
      '#type' => 'item',
      '#markup' => theme_table($table),
      );
   $count++;
  }
  return $form;
}
