<?php
/**
 * @file
 * parish.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function parish_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "feeds" && $api == "feeds_importer_default") {
    return array("version" => "1");
  }
  if ($module == "field_group" && $api == "field_group") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_node_info().
 */
function parish_node_info() {
  $items = array(
    'parish' => array(
      'name' => t('Parish'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Name'),
      'help' => '',
    ),
  );
  return $items;
}
