<?php
/**
 * @file
 * Code for the Person Data Type feature.
 */

include_once 'person_data_type.features.inc';

function person_data_type_menu() {
  $items = array();
  $items['people'] = array(
    'title' => 'People',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('person_data_type_people_form'),
    'access arguments' => array('access people listing'),
    'type' => MENU_CALLBACK,
  );
  $items['safe-training'] = array(
    'title' => 'Update Safe Training Data',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('person_data_type_safe_form'),
    'access arguments' => array('access people listing'),
    'type' => MENU_CALLBACK,
  );
  $items['partners'] = array(
    'title' => 'Partner/Marriage Editor',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('person_data_type_partners_form'),
    'access arguments' => array('access people listing'),
    'type' => MENU_CALLBACK,
  );
  $items['directory'] = array(
    'title' => 'Clergy Directory',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('person_data_type_directory_form'),
    'access arguments' => array('access clergy directory'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/****************************
  Implementation of hook_theme()
****************************/

function person_data_type_theme() {
  return array(
    'directory_person' => array(
      'variables' => array('person'=>NULL),
      'template' => 'theme/directory-person',
    ),
  );
}

function person_data_type_permission() {
  return array(
    'access people listing' => array(
      'title' => t("Access People Listing"),
      'description' => t("Allow users to view listing of all people"),
    ),
    'access clergy directory' => array(
      'title' => t("Access Clergy Directory"),
      'description' => t("Allow user to access a directory of clergy"),
    ),
  );
}

function person_data_type_partners_form($form,&$form_state) {
  $people = person_data_type_fetch_people('clergy');
  $form['single_people'] = array(
    '#theme' => 'table',
    '#caption' => 'Unpartnered People',
    '#header' => array('Person','Add'),
    '#rows'=> array(),
    '#tree' => true,
  );

  $form['partnered_people'] = array(
    '#theme' => 'table',
    '#caption' => 'Partnered People',
    '#header' => array('Person 1','Person 2','Type','edit'),
    '#rows'=> array(),
    '#tree' => true,
  );
  $expired = "";
  foreach ($people['nodes'] as $person) {
    $name = person_data_type_get_full_name($person);
    $name = l(rtrim($name," ,"),"node/".$person->nid);
    $partnerships = person_data_type_find_partnerships($person);
    $types = _partnership_types();
    $row = array();
    $row['person1'] = $name;
    $table = "single";
    $edit = l("Add Relationship","node/add/personal-relationship",array(
      'query'=>array('destination'=>"partners",'edit[field_pr_first][und]'=>$person->nid),
    ));
    $row['person2'] = "";
    foreach ($partnerships as $partnership) {
      $table = "partnered";
      if ($partnership['partner']) {
        $row['person2'] .= person_data_type_get_full_name($partnership['partner']);
      }
      else {
        $row['person2'] .= "";
      }
      $row['type'] = $types[$partnership['type']];
      if (node_access("update",$partnership['node'])) {
        $edit = l("edit","node/".$partnership['node']->nid."/edit",array(
          'query'=>array('destination'=>"partners"),
        ));
      }
    }
    $row['edit'] = $edit;
    $form[$table.'_people']['#rows'][] = array('data'=>$row);
    unset($partner_field);
    unset($type_field);
  }
  $form['submit'] = array(

    '#type' => 'submit',
    '#value' => 'Save Changes / Process CSV',
  );
  $form['#submit'] = array('person_data_type_partners_form_submit');
  return $form;
}

function person_data_type_nodereference_options($element, $edit = FALSE) {
  $field_key  = $element['#columns'][0];
  return array($field_key => NULL);
}

function person_data_type_find_partnerships($person,$inactive = FALSE) {
  $query = db_select("node","n");
  $query->leftJoin("field_data_field_pr_first","f","f.entity_id = n.nid");
  $query->leftJoin("field_data_field_pr_second","s","s.entity_id = n.nid");
  $query->leftJoin("field_data_field_pr_type","t","t.entity_id = n.nid");
  $query->leftJoin("field_data_field_pr_start","p","p.entity_id = n.nid");
  $query->leftJoin("field_data_field_pr_end","e","e.entity_id = n.nid");
  $query->leftJoin("field_data_field_pr_end_reason","r","r.entity_id = n.nid");
  $query->fields('n',array('nid'))
    ->fields('t',array('field_pr_type_value'))
    ->fields('f',array('field_pr_first_nid'))
    ->fields('s',array('field_pr_second_nid'))
    ->fields('p',array('field_pr_start_value'))
    ->fields('e',array('field_pr_end_value'))
    ->fields('r',array('field_pr_end_reason_value'))
    ->condition("n.type","personal_relationship","=")
    ->condition(db_or()->condition('t.field_pr_type_value','partnership')->condition('t.field_pr_type_value','marriage'))
    ->condition(db_or()->condition('f.field_pr_first_nid',$person->nid)->condition('s.field_pr_second_nid',$person->nid))
    ->condition('n.status', 1);
  if (!$inactive) {
    $query->isNull('e.field_pr_end_value');
    $query->isNull('r.field_pr_end_reason_value');
  }
  $result = $query->execute();
  if (!$result) {
    return false;
  }
  $partnerships = array();
  while ($record = $result->fetchAssoc()) {
    $partnership = array('type'=>$record['field_pr_type_value']);
    $partnership['start'] = "";
    if ($record['field_pr_start_value']) {
      $partnership['start'] = _date_to_human($record['field_pr_start_value']);
    }
    $partnership['end'] = "";
    if ($record['field_pr_end_value']) {
      $partnership['end'] = _date_to_human($record['field_pr_end_value']);
    }
    $partnership['end_reason'] = "";
    if ($record['field_pr_end_reason_value']) {
      $partnership['end_reason'] = $record['field_pr_end_reason_value'];
    }
    $partnership['node'] = node_load($record['nid']);
    if ($person->nid == $record["field_pr_first_nid"]) {
      $partnership['partner'] = node_load($record['field_pr_second_nid']);
    }
    elseif ($person->nid == $record['field_pr_second_nid']) {
      $partnership['partner'] = node_load($record['field_pr_first_nid']);
    }
    else {
      $partnership['partner'] = false; 
    }
    if (!empty($record['field_pr_end_value']) || !empty($record['field_pr_end_reason_value'])) {
      $partnership['active'] = FALSE;
    }
    else {
      $partnership['active'] = TRUE;
    }
    $partnerships[] = $partnership;
  }
  return $partnerships;
}

function person_data_type_partners_form_submit($form, &$form_state) {
  exit;
}


function person_data_type_safe_form($form,&$form_state) {
  $form['csv'] = array(
    '#type' => 'file',
    '#title' => "Upload a CSV",
    '#tree' => TRUE,
  );
  $people = person_data_type_fetch_people();
  $form['requireall'] = array(
    '#type' => 'checkbox',
    '#tree' => true,
    '#title' => 'Set all listed people to required',
  );
  $form['people'] = array(
    '#theme' => 'table',
    '#header' => array('Title','Required','Date','edit'),
    '#rows'=> array(),
    '#tree' => true,
  );
  $expired = "";
  foreach ($people['nodes'] as $person) {
    $name = $person->field_person_last_name['und'][0]['value'].", ";
    if (isset($person->field_person_title['und']['0']['value'])) {
      $name .= $person->field_person_title['und']['0']['value']." ";
    }
    if (isset($person->field_person_first_name['und']['0']['value'])) {
      $name .=  $person->field_person_first_name['und']['0']['value']." ";
    }
    if (isset($person->field_person_middle_name['und']['0']['value'])) {
      $name .= $person->field_person_middle_name['und']['0']['value']." ";
    }
    if (isset($person->field_person_suffix['und']['0']['value'])) {
      $name .= $person->field_person_suffix['und']['0']['value']." ";
    }
    if (isset($person->field_person_email_pref['und']['0']['value'])) {
      $email = $person->field_person_email_pref['und']['0']['value'];
    }
    $required = 0;
    if (isset($person->field_person_safe_church['und'][0]['value'])) {
      $required = $person->field_person_safe_church['und'][0]['value'];
    }
    $date = "";
    if (isset($person->field_safe_church_training_date['und'][0]['value'])) {
      $date = date('m/d/Y',$person->field_safe_church_training_date['und'][0]['value']);
    }
    $style ="";
    $expiration = strtotime("1/1/".(date('Y')-5));
    if ($required == 1 && (empty($date) || strtotime($date) < $expiration)) {
      $style = "background: #ff7777; ";
      $expired .= trim($name);
      if (isset($email)) {
        $expired.=" <".$email.">";
      }
      $expired .="\n";
    }
    $name = l(rtrim($name," ,"),"node/".$person->nid);
    $edit = "";
    if (node_access("update",$person)) {
      $edit = l("edit","node/".$person->nid."/edit");
    }
    $req_field = array(
      '#name' => 'required-'.$person->nid,
      '#type' => 'checkbox',
      '#tree' => true,
    );
    if ($required) {
      $req_field['#attributes']['checked'] = TRUE;
    }
    $date_field = array(
      '#name' => 'safedate-'.$person->nid,
      '#type'=> 'textfield',
      '#value' => $date,
      '#tree' => true,
    );
    $row = array(
      'Title' => $name,
      array('data'=>&$req_field),
      array('data'=>&$date_field),
      'edit' => $edit,
    );
    $form['people']['#rows'][] = array('data'=>$row,'style'=>$style);
    unset($req_field);
    unset($date_field);
    unset($email);
  }
  $form['expired'] = array(
    '#type'=>'textarea',
    '#value'=>$expired,
    '#title'=>'People with expired training',
    '#weight'=>-10,
  );
  $form['submit'] = array(

    '#type' => 'submit',
    '#value' => 'Save Changes / Process CSV',
  );
  $form['#submit'] = array('person_data_type_safe_form_submit');
  return $form;
}

function person_data_type_safe_form_submit($form, &$form_state) {
  $people = person_data_type_fetch_people();
  foreach ($people['nodes'] as $person) {
    if (isset($form_state['input']['requireall'])) {
      $person->field_person_safe_church['und'] = array('0' => array('value' => 1));  
    }
    elseif (isset($form_state['input']['required-'.$person->nid])) {
      $person->field_person_safe_church['und'] = array('0' => array('value' => $form_state['input']['required-'.$person->nid]));
    }
    else {
      $person->field_person_safe_church['und'] = array('0' => array('value' => 0));
    }
    if (isset($form_state['input']['safedate-'.$person->nid]) && !empty($form_state['input']['safedate-'.$person->nid])) {
      $person->field_safe_church_training_date['und'] = array('0' => array('value' => strtotime($form_state['input']['safedate-'.$person->nid])));
    }
    else {
      unset($person->field_safe_church_training_date['und'][0]);
    }
    node_save($person);
  }
  $file = file_save_upload('csv',array(
    'file_validate_extensions' => array('csv'),FILE_EXISTS_REPLACE));
  if (!$file) {
    return;
  }
  $csv = explode("\n",str_replace("\r","\n",file_get_contents(drupal_realpath($file->destination)))); 
  $header = str_getcsv($csv[0]);
  unset($csv[0]);
  $key = array();
  $key['name'] = array_shift(array_values(array_keys($header,"name")));
  $key['email'] = array_shift(array_values(array_keys($header,"email")));
  $key['date'] = array_shift(array_values(array_keys($header,"date")));
  if (is_null($key['name']) || is_null($key['email']) || is_null($key['date'])) {
    return false;
  }
  foreach ($csv as $row) {
    $data = str_getcsv($row);
    $count = 0;
    if (isset($data[$key['date']]) && !empty($data[$key['date']]) && $data[$key['name']]) {
      $date = trim($data[$key['date']]);
      $name = trim($data[$key['name']]);
      if (isset($data[$key['email']])) {
        $email = trim($data[$key['email']]);
      }
      else {
        $email = false;
      }
      $person = person_data_type_find_person($name,$email);
      if ($person) {
        if (strlen($date) == "4") {
          $date = "12/31/".$date;
        }
        $date = strtotime($date);
        $lang = $person->language; 
        $person->field_safe_church_training_date = array(
          $lang => array('0' => array('value' => $date)),
        );
        node_save($person);
      }
      else {
        drupal_set_message("Could not find ".$name.". Please update by hand.","error");
      }
    }
  }
  $form_state['rebuild'] = TRUE;  
}

function person_data_type_find_person($name,$email=FALSE) {
  $name_query = new EntityFieldQuery();
  $name_result = $name_query
    ->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'person')
    ->propertyCondition('title', "%".$name."%","LIKE")
    ->propertyCondition('status', 1)
    ->range(0,1)
    ->execute();
  if (isset($name_result['node'])) {
    $name_nid = array_shift(array_values($name_result['node']))->nid;
  }
  if (isset($name_nid)) {
    return node_load($name_nid);
  }
  if ($email) {
    $email_query = new EntityFieldQuery();
    $email_result = $email_query
      ->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', 'person')
      ->fieldCondition('field_person_email_pref','value',$email)
      ->propertyCondition('status', 1)
      ->range(0,1)
      ->execute();
    if (isset($email_result['node'])) {
      $email_nid = array_shift(array_values($email_result['node']))->nid;
    }
  }
  if (isset($email_nid)) {
    return node_load($email_nid);
  }
  return false;
}

function person_data_type_directory_form($form,&$form_state,$type="all",$last="",$first="",$status="living") {
  if (isset($form_state['values']['last'])) {
    $last = $form_state['values']['last'];
  }
  if (isset($form_state['values']['first'])) {
    $first = $form_state['values']['first'];
  }
  $people = person_data_type_fetch_people('clergy',$last,$first,$status);
  $weight = 1000;
  foreach ($people['nodes'] as $person) {
    $form['person'.$person->uid] = array(
      '#type'=>'markup',
      '#markup'=>theme('directory_person',array('person'=>$person)),
      '#weight'=>$weight,
    );
    $weight++;
  }
  $form['filters'] = array(
    '#type' => 'fieldset',
    '#title' => 'Filters',
  );
  $form['filters']['last'] = array(
    '#type' => 'textfield',
    '#default_value' => $last,
    '#title' => "Last Name",
  );
  $form['filters']['first'] = array(
    '#type' => 'textfield',
    '#default_value' => $first,
    '#title' => "First Name",
  );
  $form['filters']['submit'] = array(

    '#type' => 'submit',
    '#value' => 'Search',
  );
  $form['#submit'] = array('person_data_type_directory_form_submit');
  return $form;
}

function person_data_type_directory_form_submit($form, &$form_state) {
  if (isset($form_state['values']['type'])) {
    $form_state['values']['type'] = $form_state['values']['type'];
  }
  if (isset($form_state['values']['last'])) {
    $form_state['values']['last'] = $form_state['values']['last'];
  }
  if (isset($form_state['values']['first'])) {
    $form_state['values']['first'] = $form_state['values']['first'];
  }
  $form_state['rebuild'] = TRUE;  
}

function person_data_type_people_form($form,&$form_state,$type="all",$last="",$first="",$status="living") {
  if (isset($form_state['values']['type'])) {
    $type = $form_state['values']['type'];
  }
  if (isset($form_state['values']['last'])) {
    $last = $form_state['values']['last'];
  }
  if (isset($form_state['values']['first'])) {
    $first = $form_state['values']['first'];
  }
  if (isset($form_state['values']['status'])) {
    $status = $form_state['values']['status'];
  }
  $people = person_data_type_fetch_people($type,$last,$first,$status);
  $people_table = array(
    'header' => array('Name','Location','E-Mail','Phone','edit'),
    'rows' => array(),
    'attributes' => array(),
    'caption' => '',
    'colgroups' => array(),
    'sticky' => FALSE,
    'empty' => '',
  );
  foreach ($people['nodes'] as $person) {
    $name = $person->field_person_last_name['und'][0]['value'].", ";
    if (isset($person->field_person_title['und']['0']['value'])) {
      $name .= $person->field_person_title['und']['0']['value']." ";
    }
    if (isset($person->field_person_first_name['und']['0']['value'])) {
      $name .=  $person->field_person_first_name['und']['0']['value']." ";
    }
    if (isset($person->field_person_middle_name['und']['0']['value'])) {
      $name .= $person->field_person_middle_name['und']['0']['value']." ";
    }
    if (isset($person->field_person_suffix['und']['0']['value'])) {
      $name .= $person->field_person_suffix['und']['0']['value']." ";
    }
    $name = l(rtrim($name," ,"),"node/".$person->nid);
    $location = "";
    if (isset($person->field_person_home_city['und']['0']['value'])) {
      $location .= $person->field_person_home_city['und']['0']['value'].", ";
    }
    if (isset($person->field_person_home_state['und']['0']['value'])) {
      $location .= $person->field_person_home_state['und']['0']['value'];
    }
    if (isset($person->field_person_home_other['und']['0']['value'])) {
      $location .= $person->field_person_home_other['und']['0']['value'];
    }
    $email = "";
    if (isset($person->field_person_email_pref['und']['0']['value'])) {
      $email .= $person->field_person_email_pref['und']['0']['value'];
      $email = l($email,"mailto:".$email);
    }
    $phone = "";
    if (isset($person->field_person_phone_pref['und']['0']['value'])) {
      $phone .= $person->field_person_phone_pref['und']['0']['value'];
    }
    $edit = "";
    if (node_access("update",$person)) {
      $edit = l("edit","node/".$person->nid."/edit");
    }
    $row = array(
      'title' => $name,
      'Location' => $location,
      'E-Mail' => $email,
      'Phone' => $phone,
      'edit' => $edit,
    );
    $people_table['rows'][] = $row;
  }
  $form['filters'] = array(
    '#type' => 'fieldset',
    '#title' => 'Filters',
  );
  $form['filters']['type'] = array(
    '#type' => 'select',
    '#title' => 'Listing Type',
    '#options' => array(
      'all' => 'All',
      'clergy' => 'Clergy',
      'laity' => 'Laity',
    ),
    '#default_value' => $type,
  );
  $form['filters']['last'] = array(
    '#type' => 'textfield',
    '#default_value' => $last,
    '#title' => "Last Name",
  );
  $form['filters']['first'] = array(
    '#type' => 'textfield',
    '#default_value' => $first,
    '#title' => "First Name",
  );
  $form['filters']['status'] = array(
    '#type' => 'select',
    '#default_value' => $status,
    '#title' => "Status",
    '#options' => array('living'=>'Living','deceased'=>'Deceased'),
  );
  $form['filters']['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Search',
  );
  $form['people'] = array(
    '#type' => 'item',
    '#markup' => theme_table($people_table)
  );
  $form['#submit'] = array('person_data_type_people_form_submit');
  return $form;
}

function person_data_type_people_form_submit($form, &$form_state) {
  if (isset($form_state['values']['type'])) {
    $form_state['values']['type'] = $form_state['values']['type'];
  }
  if (isset($form_state['values']['last'])) {
    $form_state['values']['last'] = $form_state['values']['last'];
  }
  if (isset($form_state['values']['first'])) {
    $form_state['values']['first'] = $form_state['values']['first'];
  }
  $form_state['rebuild'] = TRUE;  
}

function person_data_type_fetch_people($type="all",$last="",$first="",$status="living") {
  $query = db_select("node","n");
  $query->leftJoin("field_data_field_person_last_name","l","l.entity_id = n.nid");
  $query->leftJoin("field_data_field_person_first_name","f","f.entity_id = n.nid");
  $query->leftJoin("field_data_field_person_priesthood","p","p.entity_id = n.nid");
  $query->leftJoin("field_data_field_person_diaconate","d","d.entity_id = n.nid");
  $query->leftJoin("field_data_field_person_consecration","c","c.entity_id = n.nid");
  $query->leftJoin("field_data_field_person_dod","m","m.entity_id = n.nid");
  $query->fields('n',array('nid'))
    ->condition("n.type","person","=")
    ->orderBy('l.field_person_last_name_value','ASC')
    ->orderBy('f.field_person_first_name_value','ASC')
    ->condition('n.status', 1);
  if (!empty($last)) {
    $query->condition('l.field_person_last_name_value',"%".check_plain($last)."%",'LIKE');
  }
  if (!empty($first)) {
    $query->condition('f.field_person_first_name_value',"%".check_plain($first)."%",'LIKE');
  }
  if ($status == "deceased") {
    $query->isNotNull('m.field_person_dod_value');
  }
  else {
    $query->isNull('m.field_person_dod_value');
  }
  if ($type == "clergy") {
    $is_clergy = db_or()
      ->isNotNull('p.field_person_priesthood_value')
      ->isNotNull('d.field_person_diaconate_value')
      ->isNotNull('c.field_person_consecration_value');
    $query->condition($is_clergy);
  }
  if ($type == "laity") {
    $query->isNull('p.field_person_priesthood_value')
      ->isNull('d.field_person_diaconate_value')
      ->isNull('c.field_person_consecration_value');
  }
  $result = $query->execute();
  $people = array('nodes' => array(), 'pager' => '');
  while ($record = $result->fetchAssoc()) {
    $people['nodes'][] = node_load($record['nid']);
  }
  return $people;
}

function person_data_type_is_alive($person) {
  if (field_get_items('node',$person,'field_person_dod')) {
    return false;
  }
  return true; 
}

function person_data_type_get_full_name($person) {
  $first = field_get_items('node',$person,'field_person_first_name');
  $middle = field_get_items('node',$person,'field_person_middle_name');
  $last = field_get_items('node',$person,'field_person_last_name');
  return trim(preg_replace('!\s+!', ' ', implode(" ",array(
    $first[0]['value'],
    $middle[0]['value'],
    $last[0]['value'],
  ))));
}

function person_data_type_get_address($person,$type) {
  $pfx = "field_person_".$type."_";
  $address = array(
    'line1' => _get_value($person,$pfx."1"),
    'line2' => _get_value($person,$pfx."2"),
    'city' => _get_value($person,$pfx."city"),
    'state' => _get_value($person,$pfx."state"),
    'other' => _get_value($person,$pfx."other"),
    'postal' => _get_value($person,$pfx."postal"),
  );
  return $address;
}

function person_data_type_get_phone($person,$type) {
  $pfx = "field_person_phone_".$type;
  $phone = array(
    'number' => _get_value($person,$pfx),
    'type' => _get_value($person,$pfx."_type"),
  );
  return $phone;
}

function person_data_type_get_email($person,$type) {
  $pfx = "field_person_email_".$type;
  $email = array(
    'addy' => _get_value($person,$pfx),
    'type' => _get_value($person,$pfx."_type"),
  );
  return $email;
}

function _get_value($node,$field,$type = "value") {
  $array = field_get_items('node',$node,$field);
  return $array[0][$type];
}

function person_data_type_node_load($nodes, $types) {
  if (in_array("person",$types)) {
    foreach ($nodes as $key => $node) {
      $nodes[$key]->title = person_data_type_get_full_name($node);
    }
  }
}

function person_data_type_node_view($node, $view_mode, $langcode) {
  if ($node->type == "person") {
    $count = 1;
    $partnerships = person_data_type_find_partnerships($node,TRUE);
    foreach ($partnerships as $partnership) {
      $pr_node = $partnership['node'];
      $lang = $pr_node->language;
      $nid = $pr_node->nid;
      $node->content['#group_children']['field_pr_head_'.$nid] = "group_personal_relationships";
      $node->content['#group_children']['field_pr_partnership_'.$nid] = "group_personal_relationships";
      $node->content['#group_children']['field_pr_start_'.$nid] = "group_personal_relationships";
      $node->content['#group_children']['field_pr_end_'.$nid] = "group_personal_relationships";
      $node->content['#group_children']['field_pr_end_reason_'.$nid] = "group_personal_relationships";
      if ($partnership['partner']) {
        $partner = person_data_type_get_full_name($partnership['partner']);
      }
      elseif(isset($pr_node->field_person_2_nr[$lang][0]['value'])) {
        $partner = $pr_node->field_person_2_nr[$lang][0]['value'];
      }
      else {
        $partner = "No record entered for partner/spouse";
      }
      $title = "Partnership";
      if (!$partnership['active']) {
        $title .= " (inactive)";
      }
      $node->content['field_pr_head_'.$nid] = array(
        '#theme' => 'field',
        '#label_display' => 'hidden',
        '#field_name' => 'field_pr_head',
        '#field_type' => 'textfield',
        '#view_mode' => 'full',
        '#bundle' => 'person',
        '#items' => array(0 => array('value'=>"Partnership")),
        '#formatter' => 'text_default',
        0 => array('#markup' => "<h2>".$title."</h2>"),
      );
      $node->content['field_pr_partnership_'.$nid] = array(
        '#theme' => 'field',
        '#label_display' => 'inline',
        '#field_name' => 'field_pr_partnership',
        '#field_type' => 'textfield',
        '#view_mode' => 'full',
        '#title' => ucwords($partnership['type']),
        '#bundle' => 'person',
        '#items' => array(0 => array('value'=>$partner)),
        '#formatter' => 'text_default',
        0 => array('#markup' => $partner),
      );
      $node->content['field_pr_start_'.$nid] = array(
        '#theme' => 'field',
        '#label_display' => 'inline',
        '#field_name' => 'field_pr_start_'.$nid,
        '#field_type' => 'textfield',
        '#view_mode' => 'full',
        '#title' => "Start Date",
        '#bundle' => 'person',
        '#items' => array(0 => array('value'=>$partnership['start'])),
        '#formatter' => 'text_default',
        0 => array('#markup' => $partnership['start']),
      );
   $node->content['field_pr_end_'.$nid] = array(
        '#theme' => 'field',
        '#label_display' => 'inline',
        '#field_name' => 'field_pr_end_'.$nid,
        '#field_type' => 'textfield',
        '#view_mode' => 'full',
        '#title' => "End Date",
        '#bundle' => 'person',
        '#items' => array(0 => array('value'=>$partnership['end'])),
        '#formatter' => 'text_default',
        0 => array('#markup' =>$partnership['end']),
      );
      if ($partnership['end_reason']) {
      $node->content['field_pr_end_reason_'.$nid] = array(
        '#theme' => 'field',
        '#label_display' => 'inline',
        '#field_name' => 'field_pr_end_reason_'.$nid,
        '#field_type' => 'textfield',
        '#view_mode' => 'full',
        '#title' => "Reason for End",
        '#bundle' => 'person',
        '#items' => array(0 => array('value'=>$partnership['end_reason'])),
        '#formatter' => 'text_default',
        0 => array('#markup' =>_partnership_splits($partnership['end_reason'])),
      );
      }


   
    }
  }
}

function person_data_type_form_person_node_form_alter(&$form, &$form_state, $form_id) {
    $partnerships = person_data_type_find_partnerships($form['#node'],TRUE);
    $count = 1;
    foreach ($partnerships as $partnership) {
      $pr_node = $partnership['node'];
      $lang = $pr_node->language;
      $nid = $pr_node->nid;
      $form['#group_children']['field_pr_head_'.$nid] = "group_personal_relationships";
      $form['#group_children']['field_pr_partnership_'.$nid] = "group_personal_relationships";
      $form['#group_children']['field_pr_type_'.$nid] = "group_personal_relationships";
      $form['#group_children']['field_pr_start_'.$nid] = "group_personal_relationships";
      $form['#group_children']['field_pr_end_'.$nid] = "group_personal_relationships";
      $form['#group_children']['field_pr_end_reason_'.$nid] = "group_personal_relationships";
if ($partnership['partner']) {
        $partner = person_data_type_get_full_name($partnership['partner']);
      }
    elseif(isset($pr_node->field_person_2_nr[$lang][0]['value'])) {
        $partner = $pr_node->field_person_2_nr[$lang][0]['value'];
      }
      else {
        $partner = "No record entered for partner/spouse";
      }
      $title = "Partnership";
      if (!$partnership['active']) {
        $title .= " (inactive)";
      }
      $form['field_pr_head_'.$nid] = array(
        '#type' => 'markup',
        '#markup' => '<h2>'.$title.'</h2>',
        );
      $form['field_pr_partnership_'.$nid] = array(
        '#type'=> 'item',
        '#title' => 'Partner:',
        '#markup'=>$partner,
      );
      $form['field_pr_type_'.$nid] = array(
        '#type'=> 'select',
        '#title' => 'Partnership Type:',
        '#options' => _partnership_types(),
        '#default_value' => $partnership['type'],
      );
      $form['field_pr_start_'.$nid] = array(
        '#type'=> 'textfield',
        '#title' => 'Partnership Start Date:',
        '#description' => 'Format: '.date('m/d/Y'),
        '#default_value' => $partnership['start'],
      );
      $form['field_pr_end_'.$nid] = array(
        '#type'=> 'textfield',
        '#title' => 'Partnership End Date:',
        '#description' => 'Format: '.date('m/d/Y'),
        '#default_value' => $partnership['end'],
      );
      $form['field_pr_end_reason_'.$nid] = array(
        '#type'=> 'select',
        '#title' => 'Partnership End Reason:',
        '#options' => _partnership_splits(),
        '#default_value' => $partnership['end_reason'],
      );
      $count++;
    }
}

function person_data_type_node_update($node) {
  if ($node->type == "person") {
    $partnerships = person_data_type_find_partnerships($node,TRUE);
    foreach ($partnerships as $partnership) {
      $pr_node = $partnership['node'];
      $nid = $pr_node->nid;
      $lang = $pr_node->language;
      eval("\$pr_node->field_pr_type[\$lang][0]['value']=\$node->field_pr_type_".$nid.";");
      eval("\$pr_node->field_pr_start[\$lang][0]['value'] = _date_to_utc(\$node->field_pr_start_".$nid.");");
      if (empty($pr_node->field_pr_start[$lang][0]['value'])) {
        $pr_node->field_pr_start = NULL;
      }
      eval("\$pr_node->field_pr_end[\$lang][0]['value'] = _date_to_utc(\$node->field_pr_end_".$nid.");");
      if (empty($pr_node->field_pr_end[$lang][0]['value'])) {
        $pr_node->field_pr_end = NULL;
      } 
      eval("\$pr_node->field_pr_end_reason[\$lang][0]['value']=\$node->field_pr_end_reason_".$nid.";");
      if (empty($pr_node->field_pr_end_reason[$lang][0]['value'])) {
        $pr_node->field_pr_end_reason = NULL;
      }
      node_save($pr_node);
    }
  }
}

function _date_to_utc($date) {
  if (empty($date)) {
    return "";
  }
  $object = new DateTime($date);
  return date_format($object,'Y-m-d\T00:00:00');
}

function _date_to_human($date) {
  if (empty($date)) {
    return "";
  }
  $object = new DateTime($date);
  return date_format($object,'m/d/Y');
}

function _partnership_types() {
  return array(
    ''=>'',
    'marriage'=>'Marriage',
    'partnership'=>'Partnership',
    'cohabitate'=>'Cohabitating',
    );
}

function _partnership_splits($key = FALSE) {
    $splits =  array(
      '' => '',
      "death"=>"Death",
      "divorce"=>"Divorce",
      "separation"=>"Separation",
      "other"=>"Other (see notes)",
    );
    if ($key && !empty($key)) {
      return $splits[$key];
    }
    return $splits;
}

