<?php
/**
 * Implementation of hook_menu
 */

function edb_init() {
  global $base_url;
  if ($base_url == "http://datadev.edordev.org") {
    if (module_exists("rules")) {
      module_disable(array("rules","rules_admin"));
    }
  }
  variable_set("site_frontpage","data");
  global $user;
  if (arg(1) <> "logout" && arg(0) == "user" && arg(2) <> "password" && $user->uid > 1) {
    drupal_goto("user/".$user->uid."/password");
  }
}

function edb_node_access($node, $op, $account) {
  switch ($op) {
    case "view":
      if (
        in_array("database editor",$account->roles) ||
        in_array("dean",$account->roles) ||
        $node->uid == $account->uid ||
        find_relationships(FALSE,$node) ||
        edb_check_editors($account->uid,$node)
      ) {
        return NODE_ACCESS_ALLOW;
      }
      return NODE_ACCESS_DENY;
      break;
    case "update":
      if (
        in_array("database editor",$account->roles) ||
        $node->uid == $account->uid ||
        edb_check_editors($account->uid,$node)
      ) {
        return NODE_ACCESS_ALLOW;
      }
      return NODE_ACCESS_DENY;
      break;
  }
}

function edb_is_admin() {
  global $user;
  if (
    in_array("database editor",$user->roles) ||
    in_array("dean",$user->roles) ||
    $user->uid == 1 ||
    in_array("administrator",$user->roles)) {
    return true;
  }
  return false; 
}

function edb_check_editors($uid,$node) {
  $lang = $node->language;
  if (isset($node->field_editors[$lang])) {
    foreach ($node->field_editors[$lang] as $editor) {
      if ($uid == $editor['uid']) {
        return true;
      }
    }
  }
  return false;
}
